// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkfqepeasrgxgqprmmxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrZnFlcGVhc3JneGdxcHJtbXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTAzOTEsImV4cCI6MjA2NTQ4NjM5MX0.bduT7LayJ-trmhmYXcU7L_-PBQGwh9K1a8rXlZckbcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);